routes/dashboard.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/

use App\Http\Controllers\CateringController;
use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\DishController;
use App\Http\Controllers\Dashboard\LocationController;
use App\Http\Controllers\Dashboard\LoginController;
use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\PromoController;
use App\Http\Controllers\Dashboard\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {

    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('users', 'admin.users.items')->name('users.index');
    // Route::view('users/create', 'admin.users.create')->name('users.create');
    // Route::view('users/edit', 'admin.users.edit')->name('users.edit');

    // Authentication
    Route::controller(LoginController::class)->group(function () {
        Route::get('/', 'showLoginForm')->name('admin.login');
        Route::post('/', 'login')->name('admin.login.make');
        Route::post('logout', 'logout')->name('admin.logout');
    });

    Route::middleware('auth')->group(function () {
        Route::middleware('role:super_admin')->group(function () {
            // Monitor
            Route::resource('monitor', ActivityController::class)
                ->parameters(['monitor' => 'activity'])
                ->names('monitor')
                ->only(['index', 'show']);
        });

        // Users
        Route::resource('users', UserController::class)->except(['show']);

        // Promos
        Route::resource('promos', PromoController::class)->except(['show']);

        // Menu
        Route::resource('menu', DishController::class)
            ->parameters(['menu' => 'dish'])
            ->names('menu')
            ->except(['show']);

        // Locations
        Route::resource('locations', LocationController::class)->except(['show']);

        // Recipes
        Route::resource('recipes', PostController::class)
            ->parameters(['recipes' => 'post'])
            ->names('posts')
            ->except('show');

        // Website
        Route::view('website', 'admin.website.items')->name('website.index');
        Route::view('website/home', 'admin.website.home')->name('website.home');
        Route::get('website/catering', [CateringController::class, 'index'])->name('website.catering');
        Route::post('website/catering', [CateringController::class, 'store'])->name('website.catering.store');
        Route::delete('website/catering/{catering}', [CateringController::class, 'destroy'])->name('website.catering.destroy');

        // Need role --> super_admin|admin
        Route::middleware('role:super_admin,admin')->group(function () {
            //
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Site Routes
|--------------------------------------------------------------------------
|
*/

use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;

Route::name('site.')->group(function () {

    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('/', 'home')->name('home');

    Route::get('/', [SiteController::class, 'home'])->name('home');
    Route::get('/localization/{locale}', [LocalizationController::class, 'index'])->name('localization');
    Route::get('/menu/{category:slug?}', [SiteController::class, 'menu'])->name('menu');
    Route::get('/recetas', [SiteController::class, 'blog'])->name('blog');
    Route::get('/recetas/{post:slug}', [SiteController::class, 'post'])->name('post');
    Route::get('/reserva', [SiteController::class, 'book'])->name('book');
    Route::get('/catering', [SiteController::class, 'catering'])->name('catering');
    Route::view('/nosotros', 'us')->name('us');
    Route::view('/catering/reserva', 'contact')->name('contact');
});

/*
|--------------------------------------------------------------------------
| Vue routing support
|--------------------------------------------------------------------------
|
*/

// Route::any('/{any}', 'SiteController@index')->where('any', '.*');

resources/views/blog.blade.php
@extends('layouts.default')


@section('title','Recetas | SSAM Restaurante Coreano')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="SSAM"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content="Restaurante Coreano"/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="blog">


        <v-header path="{{ Request::path() }}"></v-header>


        <main>

            <div id="title">
                <h2>Recetas.</h2>
            </div>

            <div class="navigation">
                <div class="centrador">
                    <nav>
                        <div class="link"><a href="{{ route('site.blog') }}"><span>Ver todo</span></a></div>
                        @foreach ($categories as $category)
                            <div class="link"><a href="{{ $category->link }}"><span>{{ $category->title }}</span></a></div>
                        @endforeach
                    </nav>
                </div>
            </div>

            <section id="recetas">
                <div class="centrador">
                    <div id="recipes">
                        @foreach ($posts as $post)
                            <div class="recipe">
                                <a href="{{ $post->link }}">
                                    <div class="foto">
                                        <div class="blurfoto" style="background: url('{{ $post->mainImage }}')no-repeat center center;"></div>
                                    </div>
                                </a>
                                <div class="info">
                                    <b>{{ $post->title }}</b>
                                    <span>{{ $post->description }}</span>
                                </div>
                            </div>
                        @endforeach



                    </div>
                </div>
            </section>



        </main>

    </div>

@endsection

resources/views/book.blade.php
@extends('layouts.default')


@section('title','Reserva | SSAM Restaurante Coreano')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="SSAM"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content="Restaurante Coreano"/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="book">

        <v-header path="{{ Request::path() }}"></v-header>


        <main>

            <div id="title">
                <h2>Reserva</h2>
            </div>

            <section id="reserva">
                <div class="centrador">

                    <div id="locations">


                        @foreach ($locations as $location)
                            <div class="location">
                                <div class="foto">
									<a href="{{ $location->link }}">
                                    <div class="blurfoto" :style="imgBackground('{{ $location->cover }}')"></div>
									</a>
                                </div>
                                <div class="info">
                                    <b>{{ $location->name }}</b>
                                    <p>{{ $location->address }}</p>
                                    <p>{{ $location->timetable }}</p>
                                    <p>{{ $location->contact }}</p>
									@if(filled($location->book))
									<a href="{{ $location->book }}">
										<button class="boton"><span>Reserva</span></button>
									</a>
									@endif
                                </div>
                            </div>
                        @endforeach



                    </div>

                </div>
            </section>

        </main>

    </div>

@endsection

resources/views/catering.blade.php
@extends('layouts.default')


@section('title','Catering | SSAM Restaurante Coreano')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="SSAM"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content="Restaurante Coreano"/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="catering">

        <v-header path="{{ Request::path() }}"></v-header>

        <div id="portada" class="title">
            <div class="blurfoto active" style="background: url('/images/jpg/catering.jpg')no-repeat center center;"></div>
            <div class="blurcolor"></div>
            <div class="centrador">
                <div class="centro">
                    <h2>Catering.</h2>
                </div>
            </div>
        </div>

        <main>

            <section id="eventos">
                <div class="centrador">

                    <div class="info">
                        <h6>Catering en Guadalajara</h6>
                        <p class="paragraph">Nuestros restaurantes en Guadalajara ofrecen una variedad de opciones para eventos especiales y privados, incluyendo recepciones corporativas y de negocios.

                            Por favor haz clic en el botón para llenar la forma y podamos ponernos en contacto contigo.</p>
                    </div>


                    <div class="info" id="paquetes">
                        <h6>Paquetes</h6>

                        @foreach ($caterings as $catering)
                            <div class="paquete">
                                <b>{{ $catering->title }}</b>
                                <p class="paragraph">{{ $catering->description }}</p>
                            </div>
                        @endforeach


                    </div>

                    <div id="actions"><a href="{{ route('site.contact') }}"><button class="boton"><span>Llenar forma de solicitud</span></button></a></div>

                </div>
            </section>


        </main>


    </div>

@endsection

resources/views/contact.blade.php
@extends('layouts.default')

@section('title','Solicitud de Catering | SSAM Restaurante Coreano')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="SSAM"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content="Restaurante Coreano"/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="contact">
	    
		
		<v-header path="{{ Request::path() }}"></v-header>
        
		
		<main>
	    
		    <div id="title">
			    <h2>Catering.</h2>
		    </div>
		    
		    <section id="solicitud">
			    <div class="centrador">
				    
				    <Contacto></Contacto>
				    
			    </div>
		    </section>
		    
		    
		</main>
        

    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.default')


@section('title','SSAM - Restaurante Coreano')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="SSAM"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content="Restaurante Coreano"/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="site">


        <v-header path="{{ Request::path() }}"></v-header>

        <Cover :photos="{{ Js::from($covers ?? []) }}"></Cover>


    </div>

@endsection

resources/views/menu.blade.php
@extends('layouts.default')


@section('title','Menú | SSAM Restaurante Coreano')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="SSAM"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content="Restaurante Coreano"/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="themenu">


        <v-header path="{{ Request::path() }}"></v-header>

        <Promos :promos="{{ Js::from($promos ?? []) }}"></Promos>

        <main>

            <div class="navigation" id="top">
                <div class="centrador">
                    <nav>
                        <div class="link"><a href="{{ route('site.menu') }}"><span>Ver todo</span></a></div>
                        @foreach ($categories as $category)
                            <div class="link"><a href="{{ $category->link }}"><span>{{ $category->title }}</span></a></div>
                        @endforeach
                    </nav>
                </div>
            </div>


            <section id="menu">
                <div class="centrador">

                    @foreach ($groups as $category => $dishes)
                        <div class="categoria">
                            <h6>{{ $category }}</h6>
                            <div class="platos">


                                @foreach ($dishes as $dish)
                                    <div class="plato">
                                        <div class="foto">
                                            <div class="blurfoto" :style="imgBackground('{{ $dish->cover }}')"></div>
                                        </div>
                                        <div class="info">
                                            <b>{{ $dish->title }}</b>
                                            <span>{{ $dish->description }}</span>
                                        </div>
                                    </div>
                                @endforeach





                            </div>
                        </div>
                    @endforeach

                </div>
            </section>


            <div class="navigation" id="bottom">
                <div class="centrador">
                    <nav>
                        <div class="link"><a href="{{ route('site.menu') }}"><span>Ver todo</span></a></div>
                        @foreach ($categories as $category)
                            <div class="link"><a href="{{ $category->link }}"><span>{{ $category->title }}</span></a></div>
                        @endforeach
                    </nav>
                </div>
            </div>

        </main>


    </div>

@endsection

resources/views/post.blade.php
@extends('layouts.default')

@section('title', '$post->title'. ' | SSAM Restaurante Coreano')

@section('metas')


   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="{{ $post->title }}"/>
	<meta property="og:image" content="{{-- $post->cover --}}"/>
	<meta property="og:description" content="{{ optional($post)->previewText() }}"/>
	<meta property="fb:app_id" content=""/>


@endsection


@section('content')

    <div id="post">


        <v-header path="{{ Request::path() }}"></v-header>

        <Gallery :photos="{{ Js::from($post->images ?? []) }}"></Gallery>


        {{-- $post->title --}}
        {{-- $post->description --}}
        {{-- $post->created_at->format('d/m/Y') --}}


        <main>

            <article>
                <div class="centrador">


                    <div id="bloques">


                        @foreach ($post->blocks->sortBy('position') as $block)
                            @switch($block->layout)
                                @case('title')
                                    <div class="bloque title">
                                        <h6>{{ $block->extractContent('text') }}</h6>
                                    </div>
                                @break

                                @case('text')
                                    <div class="bloque text">
                                        <p class="paragraph">{{ $block->extractContent('text') }}</p>
                                    </div>
                                @break

                                @case('list')
                                    <div class="bloque list">
                                        @foreach ($block->extractContent('items') ?? [] as $item)
                                            <p class="paragraph">{{ $item }}</p>
                                        @endforeach
                                    </div>
                                @break
                            @endswitch
                        @endforeach



                    </div>

                    <div id="actions"><a href="{{ route('site.blog') }}"><button class="boton"><span>Volver a recetas</span></button></a></div>

                </div>
            </article>



        </main>

		{{-- <Sharer url="{{ Request::url() }}"></Sharer> --}}
		
		



    </div>

@endsection

resources/views/site.blade.php
@extends('layouts.default')

@section('title','Planetoide.mx')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="Planetoide.mx"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content=""/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="site">

        <app></app>

    </div>

@endsection


@push('scripts')

	<script>
        {{-- Si no habrá scripts eliminar este @push  --}}
	</script>

@endpush

resources/views/us.blade.php
@extends('layouts.default')

@section('title','Nosotros | SSAM Restaurante Coreano')

@section('metas')

   	<meta property="og:url" content="{{ Request::url() }}"/>
	<meta property="og:type" content="website"/>
	<meta property="og:title" content="SSAM"/>
	<meta property="og:image" content="{{ asset('images/meta_img.jpg') }}"/>
	<meta property="og:description" content="Restaurante Coreano"/>
	<meta property="fb:app_id" content=""/>

@endsection


@section('content')

    <div id="us">
	    
		
        <v-header path="{{ Request::path() }}"></v-header>
        
        <div id="portada" class="title">
	        <div class="blurfoto active" style="background: url('/images/jpg/us.jpg')no-repeat center center;"></div>
	        <div class="blurcolor"></div>
	        <div class="centrador">
		        <div class="centro">
			        <h2>Nosotros.</h2>
		        </div>
	        </div>
        </div>
        
        <main>
	    
	        
	        
	        <section class="texto">
		        <div class="centrador">
			        <div class="parrafos">
				        <div class="parrafo full">
					        <div class="centro">
						        <h6>Cómo empezó todo</h6>
						        <p class="paragraph">SSAM nace en 2014 como una propuesta de desayunos mexicanos y comida corrida, sin embargo, a los 6 meses de la apertura se incluyó en el menú el primer platillo coreano y tuvo tal éxito que la gente comenzó a pedirlo cada vez más.

Con el paso del tiempo, se ofreció comida mexicana por las mañanas y coreana por las tardes, pues los clientes ya se habían enamorado de los sabores de esta gastronomía. 

Finalmente, dos años después de la creación del restaurante el concepto cambió totalmente a como lo conocemos ahora, ofreciendo comida coreana en un ambiente moderno y acogedor.

Hoy, somos una gran comunidad formada por nuestros colaboradores, clientes y proveedores, todos juntos somos SSAM.</p>
							</div>
				        </div>
			        </div>
		        </div>
	        </section>
	        
	        
	        <section class="photo">
		        <div class="centrador">
			        <div class="fotos">
				        <div class="foto full">
					        <img src="/images/jpg/us1.jpg">
				        </div>
			        </div>
		        </div>
	        </section>
	        
	        
	        <section class="texto">
		        <div class="centrador">
			        <div class="parrafos">
				        <div class="parrafo">
					        <div class="centro">
					        	<h6>Su</h6>
								<p class="paragraph">Originaria de Jecheon, Corea del Sur. Joven emprendedora, dueña de la colección de restaurantes coreanos más reconocidos de Guadalajara.

Sujin Lee es una mujer apasionada por compartir la gastronomía y cultura de su país de origen, mismo sueño que ha trasladado a su modelo de empresa, donde el propósito es la globalización de la comida coreana creando experiencias gastronómicas inolvidables.
 
Además de su labor como empresaria, Sujin Lee está presente en la red social Instagram como Su.de.ssam en donde comparte su día a día como coreana, mamá y experta de comida con el mismo principio que ha transmitido a sus restaurantes, donde representa a su cultura y ha generado una gran comunidad.</p>
							</div>
				        </div>
				        <div class="parrafo">
					        <div class="centro">
					        	<h6>César</h6>
					        	<p class="paragraph">Originario de Guadalajara Jalisco, licenciado en administración de restaurantes por la Universidad Anáhuac y cocinero de profesión.

Junto a Sujin creó el menú y estructura operativa de la colección de restaurantes SSAM.

Actualmente César Cárdenas está al frente de la dirección de SSAM, donde en conjunto con el equipo buscan crear experiencias gastronómicas inolvidables, expansión de marca y contribuir al desarrollo personal y profesional de sus colaboradores.</p>
							</div>
				        </div>
			        </div>
		        </div>
	        </section>
	        
	        
	        <section class="photo">
		        <div class="centrador">
			        <div class="fotos">
				        <div class="foto full">
					        <img src="/images/jpg/us2.jpg">
				        </div>
			        </div>
		        </div>
	        </section>
	        
	        
	        <section class="texto">
		        <div class="centrador">
			        <div class="parrafos">
				        <div class="parrafo full">
					        <div class="centro">
					        	<h6>Nuestra comida</h6>
								<p class="paragraph">Somos una colaboración de dos restauranteros y chefs, César Cárdenas y Sujin Lee, juntos con el gran sueño de globalizar la gastronomía coreana creamos la primera sucursal en la calle José María Morelos, colonia Ladrón de Guevara, Jalisco.

En 2022, SSAM fue posicionado como el número uno elegido por los usuarios de la plataforma internacional Tripadvisor.

Cocinamos con amor por la tradición coreana, siempre con un alto enfoque en la innovación y la calidad de los alimentos, desde la selección de los ingredientes hasta que llevamos los platos a tu mesa.

Deja que la calidez de un Ramyeon, la explosión de sabores de un Bibimbap o los condimentos del Kimchi te regalen un pedacito de Corea.</p>
							</div>
				        </div>
			        </div>
		        </div>
	        </section>
	        
	        
	        
	        <section class="photo">
		        <div class="centrador">
			        <div class="fotos">
				        <div class="foto">
					        <div class="blurfoto" style="background: url('/images/jpg/us3.jpg')no-repeat center center;"></div>
				        </div>
				        <div class="foto">
					        <div class="blurfoto" style="background: url('/images/jpg/us4.jpg')no-repeat center center;"></div>
				        </div>
			        </div>
		        </div>
	        </section>
	
	        
        </main>
        

    </div>

@endsection