routes/dashboard.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/

use App\Http\Controllers\CateringController;
use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\DishController;
use App\Http\Controllers\Dashboard\LocationController;
use App\Http\Controllers\Dashboard\LoginController;
use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\PromoController;
use App\Http\Controllers\Dashboard\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {

    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('users', 'admin.users.items')->name('users.index');
    // Route::view('users/create', 'admin.users.create')->name('users.create');
    // Route::view('users/edit', 'admin.users.edit')->name('users.edit');

    // Authentication
    Route::controller(LoginController::class)->group(function () {
        Route::get('/', 'showLoginForm')->name('admin.login');
        Route::post('/', 'login')->name('admin.login.make');
        Route::post('logout', 'logout')->name('admin.logout');
    });

    Route::middleware('auth')->group(function () {
        Route::middleware('role:super_admin')->group(function () {
            // Monitor
            Route::resource('monitor', ActivityController::class)
                ->parameters(['monitor' => 'activity'])
                ->names('monitor')
                ->only(['index', 'show']);
        });

        // Users
        Route::resource('users', UserController::class)->except(['show']);

        // Promos
        Route::resource('promos', PromoController::class)->except(['show']);

        // Menu
        Route::resource('menu', DishController::class)
            ->parameters(['menu' => 'dish'])
            ->names('menu')
            ->except(['show']);

        // Locations
        Route::resource('locations', LocationController::class)->except(['show']);

        // Recipes
        Route::resource('recipes', PostController::class)
            ->parameters(['recipes' => 'post'])
            ->names('posts')
            ->except('show');

        // Website
        Route::view('website', 'admin.website.items')->name('website.index');
        Route::view('website/home', 'admin.website.home')->name('website.home');
        Route::get('website/catering', [CateringController::class, 'index'])->name('website.catering');
        Route::post('website/catering', [CateringController::class, 'store'])->name('website.catering.store');
        Route::delete('website/catering/{catering}', [CateringController::class, 'destroy'])->name('website.catering.destroy');

        // Need role --> super_admin|admin
        Route::middleware('role:super_admin,admin')->group(function () {
            //
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Site Routes
|--------------------------------------------------------------------------
|
*/

use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;

Route::name('site.')->group(function () {

    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('/', 'home')->name('home');

    Route::get('/', [SiteController::class, 'home'])->name('home');
    Route::get('/localization/{locale}', [LocalizationController::class, 'index'])->name('localization');
    Route::get('/menu/{category:slug?}', [SiteController::class, 'menu'])->name('menu');
    Route::get('/recetas', [SiteController::class, 'blog'])->name('blog');
    Route::get('/recetas/{post:slug}', [SiteController::class, 'post'])->name('post');
    Route::get('/reserva', [SiteController::class, 'book'])->name('book');
    Route::get('/catering', [SiteController::class, 'catering'])->name('catering');
    Route::view('/nosotros', 'us')->name('us');
    Route::view('/catering/reserva', 'contact')->name('contact');
});

/*
|--------------------------------------------------------------------------
| Vue routing support
|--------------------------------------------------------------------------
|
*/

// Route::any('/{any}', 'SiteController@index')->where('any', '.*');

resources/views/admin/menu/create.blade.php
@extends('admin.menu.items')

{{-- Seccion de Form --}}
@section('form')
    <div class="formularios white" id="menu_form">

        <form action="{{ route('menu.store') }}" method="POST" enctype="multipart/form-data" ref="formCreate">
            @csrf

            <div class="fotos">
                <div class="foto">
                    <input type="file" name="cover" @change="setImage" accept="image/*">
                    <div class="type">
                        <i class="fa fa-image" aria-hidden="true"></i>
                        <label>Foto</label>
                    </div>
                </div>
            </div>

            <div class="input">
                <label>Categoría</label>
                <select name="category">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->title }}</option>
                    @endforeach
                </select>
                <div class="focus"></div>
            </div>

            <div class="input">
                <label>Plato</label>
                <input type="text" name="title" value="{{ old('title') }}" placeholder="Plato">
                <div class="focus"></div>
            </div>

            <div class="input">
                <label>Descripción</label>
                <textarea name="description" placeholder="Descripción" rows="6">{{ old('description') }}</textarea>
                <div class="focus"></div>
            </div>

            <button type="button" @click="saveWithSpinner($refs.formCreate)">Done</button>

        </form>


    </div>


    <panel-change-view view="edit_view"></panel-change-view>

    <panel-config :actions="['hideActions', 'hidePreview']"></panel-config>
@endsection
{{-- Seccion de Form --}}

resources/views/admin/menu/edit.blade.php
@extends('admin.menu.items')


{{-- Seccion View --}}
@section('preview')
    <div id="menu_preview">

    </div>
@endsection
{{-- Seccion View --}}


{{-- Seccion de Form --}}
@section('form')
    <div class="formularios white" id="menu_form">

        <form action="{{ route('menu.update', compact('dish')) }}" method="POST" enctype="multipart/form-data" ref="formEdit">
            @csrf
            @method('PUT')

            <div class="fotos">
                <div class="foto" :style="imgBackground('{{ $dish->cover }}')">
                    <input type="file" name="cover" @change="setImage" accept="image/*">
                    <div class="type">
                        <i class="fa fa-image" aria-hidden="true"></i>
                        <label>Foto</label>
                    </div>
                </div>
            </div>

            <div class="input">
                <label>Categoría</label>
                <select name="category">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}" @selected($category->id === $dish->category->id)>{{ $category->title }}</option>
                    @endforeach
                </select>
                <div class="focus"></div>
            </div>

            <div class="input">
                <label>Plato</label>
                <input type="text" name="title" value="{{ old('title', $dish) }}" placeholder="Plato">
                <div class="focus"></div>
            </div>

            <div class="input">
                <label>Descripción</label>
                <textarea name="description" placeholder="Descripción" rows="6">{{ old('description', $dish) }}</textarea>
                <div class="focus"></div>
            </div>

            <div class="input check">
                <input type="hidden" name="show_in_menu" value="0">
                <input type="checkbox" name="show_in_menu" value="1" @checked($dish->show_in_menu)>
                <div class="checkbox">
                    <i class="fa fa-check" aria-hidden="true"></i>
                </div>
                <label>Mostrar en Menu</label>
            </div>


            <button type="button" @click="saveWithSpinner($refs.formEdit)">Done</button>

        </form>



    </div>


    <panel-change-view view="edit_view"></panel-change-view>

    <panel-config :actions="['hideActionShow', 'hidePreview']"></panel-config>

    <panel-delete-item message="Delete this plate?" delete-route="{{ route('menu.destroy', compact('dish')) }}"></panel-delete-item>
@endsection
{{-- Seccion de Form --}}

resources/views/admin/menu/items.blade.php
@extends('admin.dashboard')

@section('title', 'Admin | Menu')

@section('bar_title', 'Menu')

@section('search_route', 'menu.index')

{{-- Seccion de items --}}
@section('items')

    <a href="{{ route('menu.create') }}">
        <div class="item menu_item new">
            <label>Nuevo Platillo</label>
        </div>
    </a>

    @foreach ($dishes as $dish)
        <a href="{{ route('menu.edit', compact('dish')) }}">
            <div class="item menu_item">

                <div class="foto" :style="imgBackground('{{ $dish->cover }}')"></div>

                <div class="texto">
                    <strong>{{ $dish->title }}</strong>
                    <span>{{ $dish->category->title }}</span>
                </div>

            </div>
        </a>
    @endforeach

    {{ $dishes->links() }}

    <panel-config :actions="['hideFilters', 'hideSearch']"></panel-config>


@endsection

{{-- Seccion de items --}}