routes/dashboard.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/

use App\Http\Controllers\CateringController;
use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\DishController;
use App\Http\Controllers\Dashboard\LocationController;
use App\Http\Controllers\Dashboard\LoginController;
use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\PromoController;
use App\Http\Controllers\Dashboard\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {

    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('users', 'admin.users.items')->name('users.index');
    // Route::view('users/create', 'admin.users.create')->name('users.create');
    // Route::view('users/edit', 'admin.users.edit')->name('users.edit');

    // Authentication
    Route::controller(LoginController::class)->group(function () {
        Route::get('/', 'showLoginForm')->name('admin.login');
        Route::post('/', 'login')->name('admin.login.make');
        Route::post('logout', 'logout')->name('admin.logout');
    });

    Route::middleware('auth')->group(function () {
        Route::middleware('role:super_admin')->group(function () {
            // Monitor
            Route::resource('monitor', ActivityController::class)
                ->parameters(['monitor' => 'activity'])
                ->names('monitor')
                ->only(['index', 'show']);
        });

        // Users
        Route::resource('users', UserController::class)->except(['show']);

        // Promos
        Route::resource('promos', PromoController::class)->except(['show']);

        // Menu
        Route::resource('menu', DishController::class)
            ->parameters(['menu' => 'dish'])
            ->names('menu')
            ->except(['show']);

        // Locations
        Route::resource('locations', LocationController::class)->except(['show']);

        // Recipes
        Route::resource('recipes', PostController::class)
            ->parameters(['recipes' => 'post'])
            ->names('posts')
            ->except('show');

        // Website
        Route::view('website', 'admin.website.items')->name('website.index');
        Route::view('website/home', 'admin.website.home')->name('website.home');
        Route::get('website/catering', [CateringController::class, 'index'])->name('website.catering');
        Route::post('website/catering', [CateringController::class, 'store'])->name('website.catering.store');
        Route::delete('website/catering/{catering}', [CateringController::class, 'destroy'])->name('website.catering.destroy');

        // Need role --> super_admin|admin
        Route::middleware('role:super_admin,admin')->group(function () {
            //
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Site Routes
|--------------------------------------------------------------------------
|
*/

use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;

Route::name('site.')->group(function () {

    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('/', 'home')->name('home');

    Route::get('/', [SiteController::class, 'home'])->name('home');
    Route::get('/localization/{locale}', [LocalizationController::class, 'index'])->name('localization');
    Route::get('/menu/{category:slug?}', [SiteController::class, 'menu'])->name('menu');
    Route::get('/recetas', [SiteController::class, 'blog'])->name('blog');
    Route::get('/recetas/{post:slug}', [SiteController::class, 'post'])->name('post');
    Route::get('/reserva', [SiteController::class, 'book'])->name('book');
    Route::get('/catering', [SiteController::class, 'catering'])->name('catering');
    Route::view('/nosotros', 'us')->name('us');
    Route::view('/catering/reserva', 'contact')->name('contact');
});

/*
|--------------------------------------------------------------------------
| Vue routing support
|--------------------------------------------------------------------------
|
*/

// Route::any('/{any}', 'SiteController@index')->where('any', '.*');

app/Models/Promo.php
<?php

namespace App\Models;

use App\Asteroide\Traits\FileUrls;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;

class Promo extends Model
{
    use FileUrls;

    /**
     * Fields that can be mass assigned.
     *
     * @var array
     */
    protected $fillable = [
        'text',
        'cover_image_path',
    ];

    /**
     * The accessors to append to the model’s array form.
     *
     * @var array<string>
     */
    protected $appends = [
        'cover',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'created_at',
        'updated_at',
        'cover_image_path',
    ];

    /**
     * Get the promo's cover.
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    public function cover(): Attribute
    {
        return new Attribute(
            get: fn () => $this->fileUrl('cover_image_path'),
        );
    }
}

app/Http/Controllers/Dashboard/PromoController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Asteroide\Traits\ControllerHelpers;
use App\Asteroide\Traits\DealWithFiles;
use App\Asteroide\Traits\Notifications;
use App\Http\Controllers\Controller;
use App\Http\Requests\PromoRequest;
use App\Models\Promo;

class PromoController extends Controller
{
    use Notifications,
        ControllerHelpers,
        DealWithFiles;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $promos = Promo::paginate($this->itemsPerPage);

        return view('admin.promos.items', compact('promos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $promos = Promo::paginate($this->itemsPerPage);

        return view('admin.promos.create', compact('promos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\PromoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PromoRequest $request)
    {
        $promo = Promo::create($request->all() + [
            'cover_image_path' => $request->hasFile('cover') ? $this->saveFile('promos', $request->cover) : null,
        ]);

        return redirect()->route('promos.edit', compact('promo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Promo  $promo
     * @return \Illuminate\Http\Response
     */
    public function edit(Promo $promo)
    {
        $promos = Promo::paginate($this->itemsPerPage);

        return view('admin.promos.edit', compact('promos', 'promo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\PromoRequest  $request
     * @param  \App\Promo  $promo
     * @return \Illuminate\Http\Response
     */
    public function update(PromoRequest $request, Promo $promo)
    {
        $promo->fill($request->all());

        if ($request->hasFile('cover')) {
            $this->deleteFile($promo->cover_image_path);

            $promo->cover_image_path = $this->saveFile('promos', $request->cover);
        }

        $promo->save();

        $this->prepareNotification($request);

        return redirect()->route('promos.edit', compact('promo'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Promo  $promo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Promo $promo)
    {
        $this->deleteFile($promo->cover_image_path);

        $promo->delete();

        $this->prepareNotification(request());

        return redirect()->route('promos.index');
    }
}

resources/views/admin/promos/create.blade.php
@extends('admin.promos.items')

{{-- Seccion de Form --}}
@section('form')
    <div class="formularios white" id="promo_form">

        <form action="{{ route('promos.store') }}" method="POST" enctype="multipart/form-data" ref="createForm">
            @csrf

            <div class="fotos">
                <div class="foto">
                    <input type="file" name="cover" @change="setImage" accept="image/*">
                    <div class="type">
                        <i class="fa fa-photo" aria-hidden="true"></i>
                        <label>Imagen</label>
                    </div>
                </div>
            </div>

            <div class="input">
                <label>Promo</label>
                <input type="text" name="text" value="{{ old('text') }}" placeholder="Promo">
                <div class="focus"></div>
            </div>

            <button type="button" @click="saveWithSpinner($refs.createForm)">Done</button>

        </form>


    </div>

    <panel-change-view view="edit_view"></panel-change-view>

    <panel-config :actions="['hideActions', 'hidePreview']"></panel-config>
@endsection
{{-- Seccion de Form --}}

resources/views/admin/promos/edit.blade.php
@extends('admin.promos.items')


{{-- Seccion View --}}

@section('preview')
    <div id="promo_preview">

    </div>
@endsection

{{-- Seccion View --}}





{{-- Seccion de Form --}}

@section('form')
    <div class="formularios white" id="promo_form">

        <form action="{{ route('promos.update', compact('promo')) }}" method="POST" enctype="multipart/form-data" ref="updateForm">
            @csrf
            @method('PUT')

            <div class="fotos">
                <div class="foto" :style="imgBackground('{{ $promo->cover }}')">
                    <input type="file" name="cover" @change="setImage" accept="image/*">
                    <div class="type">
                        <i class="fa fa-image" aria-hidden="true"></i>
                        <label>Imagen</label>
                    </div>
                </div>
            </div>

            <div class="input">
                <label>Promo</label>
                <input type="text" name="text" value="{{ old('text', $promo) }}" placeholder="Promo">
            </div>

            <button type="button" @click="saveWithSpinner($refs.updateForm)">Done</button>

        </form>



    </div>

    <panel-change-view view="edit_view"></panel-change-view>

    <panel-config :actions="['hideActionShow', 'hidePreview']"></panel-config>

    <panel-delete-item message="Delete this highlight?" delete-route="{{ route('promos.destroy', compact('promo')) }}"></panel-delete-item>
@endsection
{{-- Seccion de Form --}}

resources/views/admin/promos/items.blade.php
@extends('admin.dashboard')

@section('title', 'Admin | Highlights')

@section('bar_title', 'Highlights')

{{-- Seccion de items --}}
@section('items')

    <a href="{{ route('promos.create') }}">
        <div class="item promo_item new">
            <label>Nuevo promo</label>
        </div>
    </a>

    @foreach ($promos as $promo)
        <a href="{{ route('promos.edit', compact('promo')) }}">
            <div class="item promo_item">
                <div class="foto" :style="imgBackground('{{ $promo->cover }}')"></div>
            </div>
        </a>
    @endforeach

    {{ $promos->links() }}

    <panel-config :actions="['hideFilters', 'hideSearch']"></panel-config>

@endsection

{{-- Seccion de items --}}